### ISSUE TITLE
Allow setting column-wide styles

### ISSUE THREAD

**Issue by LoadingByte** [rabanti-github/NanoXLSX4j#3]
When writing a template that the user will later edit, it's useful to specify the style of an entire column, so that any content he writes below the template rows also has the style applied. In XLSX that's afaik done by setting the `style` attribute on the `col` element in the `xl/worksheets/sheet#.xml` file; at least that's what Apache POI does when calling the [Sheet.setDefaultColumnStyle](https://poi.apache.org/apidocs/dev/org/apache/poi/ss/usermodel/Sheet.html#setDefaultColumnStyle-int-org.apache.poi.ss.usermodel.CellStyle-) method:

```xml
<col min="5" max="5" ... style="1" />
```

Right now, NanoXLSX4j has no provision for writing this attribute:

https://github.com/rabanti-github/NanoXLSX4j/blob/8ae7678b70cc4af287cc6adfd03d7d258ac56cd2/NanoXLSX4j.Lib/src/main/java/ch/rabanti/nanoxlsx4j/lowLevel/XlsxWriter.java#L187-L188

Would it be possible to add a facility to write it?

**Comment by rabanti-github** [comment]
Hi,
The feature was implemented in the new release v2.4.0.
Please let me know if something is not working as expected.

**Comment by LoadingByte** [comment]
Everything works as expected.
